/**
 * Copyright (c) 2024 Martin Bechard <martin.bechard@DevConsult.ca>
 * This software is licensed under the MIT License.
 * File: tests/services/AliasService.test.ts
 * This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
 */

import { describe, expect, it, beforeEach } from "@jest/globals";
import { AliasService } from "../../src/services/AliasService";
import { MemoryStorage } from "../../src/types/storage";

describe("AliasService", () => {
  beforeEach(() => {
    // Initialize with fresh MemoryStorage for each test
    AliasService.initialize(new MemoryStorage());
    AliasService.clearAllAliases();
  });

  describe("setAlias", () => {
    it("should store a valid alias", () => {
      AliasService.setAlias("test", "Hello World");
      expect(AliasService.getAlias("test")).toBe("Hello World");
    });

    it("should throw error for invalid alias name", () => {
      expect(() => AliasService.setAlias("test-invalid", "Hello")).toThrow(
        "Invalid alias name"
      );
    });
  });

  describe("deleteAlias", () => {
    it("should delete existing alias", () => {
      AliasService.setAlias("test", "Hello World");
      expect(AliasService.deleteAlias("test")).toBe(true);
      expect(AliasService.getAlias("test")).toBeUndefined();
    });

    it("should return false for non-existent alias", () => {
      expect(AliasService.deleteAlias("nonexistent")).toBe(false);
    });
  });

  describe("processText", () => {
    beforeEach(() => {
      AliasService.setAlias("hello", "Hello World");
      AliasService.setAlias("nested", "@hello there");
    });

    it("should replace simple aliases", () => {
      expect(AliasService.processText("@hello")).toBe("Hello World");
    });

    it("should handle nested aliases", () => {
      expect(AliasService.processText("@nested")).toBe("Hello World there");
    });

    it("should handle multiple aliases in text", () => {
      expect(AliasService.processText("@hello @hello")).toBe(
        "Hello World Hello World"
      );
    });

    it("should not replace partial matches", () => {
      expect(AliasService.processText("email@hello.com")).toBe(
        "email@hello.com"
      );
    });
  });

  describe("getAliasList", () => {
    it("should return formatted list of aliases", () => {
      AliasService.setAlias("test1", "Value 1");
      AliasService.setAlias("test2", "Value 2");
      const list = AliasService.getAliasList();
      expect(list).toContain("@test1: Value 1");
      expect(list).toContain("@test2: Value 2");
    });
  });
});
