/**
 * Copyright (c) 2024 Martin Bechard <martin.bechard@DevConsult.ca>
 * This software is licensed under the MIT License.
 * File: /Users/martinbechard/dev/claudeext/src/ui/components/ContentPreview.ts
 * This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
 */

import { DraggableManager } from "./DraggableManager";
import { ThemeManager, ThemeColors } from "../theme";

declare global {
  interface Window {
    Prism?: {
      highlight: (code: string, grammar: any, language: string) => string;
      languages: { [key: string]: any };
    };
    marked?: {
      parse: (markdown: string, options?: any) => string;
    };
  }
}

const spacing = {
  sm: "8px",
  md: "16px",
  lg: "24px",
};

const fontSize = {
  sm: "14px",
  md: "16px",
  lg: "18px",
};

const borderRadius = "8px";

export class ContentPreview {
  private readonly dialog: HTMLElement;
  private readonly content: HTMLElement;
  private readonly header: HTMLElement;
  private isOpen: boolean = false;
  private draggableManager: DraggableManager;
  private static baseZIndex: number = 1000003;
  private static windowCount: number = 0;
  private colors: ThemeColors;
  private markdownStyle: HTMLStyleElement | null = null;
  private closeButton: HTMLButtonElement | null = null;

  constructor() {
    this.colors = ThemeManager.getColors();
    this.dialog = document.createElement("div");
    this.content = document.createElement("div");
    this.header = document.createElement("div");
    this.createDialog();
    this.draggableManager = new DraggableManager(this.dialog, this.header);

    // Listen for theme changes
    ThemeManager.addThemeChangeListener(() => {
      this.colors = ThemeManager.getColors();
      this.updateTheme();
    });
  }

  private updateTheme(): void {
    if (!this.isOpen) return;

    this.content.style.background = this.colors.background;
    this.header.style.borderBottom = `1px solid ${this.colors.border}`;

    // Update markdown styles if they exist
    if (this.markdownStyle) {
      this.markdownStyle.textContent = this.getMarkdownStyles();
    }

    // Update any code blocks
    const codeContainer = this.content.querySelector('[class*="language-"]');
    if (codeContainer) {
      (codeContainer as HTMLElement).style.background = this.colors.codeBg;
    }

    // Update close button
    if (this.closeButton) {
      this.closeButton.style.color = this.colors.text;
    }
  }

  private createDialog(): void {
    this.dialog.style.cssText = `
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        width: 800px;
        max-width: 90%;
        max-height: 80vh;
        z-index: ${ContentPreview.baseZIndex};
        display: none;
      `;

    this.content.style.cssText = `
        background: ${this.colors.background};
        border-radius: ${borderRadius};
        width: 100%;
        height: 100%;
        display: flex;
        flex-direction: column;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
        position: relative;
      `;

    this.header.style.cssText = `
        padding: ${spacing.md};
        border-bottom: 1px solid ${this.colors.border};
        cursor: move;
      `;

    this.dialog.appendChild(this.content);
    document.body.appendChild(this.dialog);

    document.addEventListener("keydown", (e) => {
      if (e.key === "Escape" && this.isOpen) {
        this.close();
      }
    });
  }

  private getLanguageFromFileName(fileName: string): string {
    const parts = fileName.split(".");
    if (parts.length === 1) {
      return "markdown";
    }

    const ext = parts.pop()?.toLowerCase() || "";
    const languageMap: { [key: string]: string } = {
      js: "javascript",
      ts: "typescript",
      jsx: "javascript",
      tsx: "typescript",
      py: "python",
      java: "java",
      rb: "ruby",
      go: "go",
      rs: "rust",
      cpp: "cpp",
      c: "c",
      cs: "csharp",
      php: "php",
      html: "html",
      css: "css",
      json: "json",
      md: "markdown",
      yml: "yaml",
      yaml: "yaml",
      xml: "xml",
      sql: "sql",
      sh: "bash",
      bash: "bash",
      txf: "markdown",
    };
    return languageMap[ext] || "plaintext";
  }

  private createCloseButton(): HTMLButtonElement {
    const button = document.createElement("button");
    button.innerHTML = "×";
    button.style.cssText = `
        position: absolute;
        top: ${spacing.sm};
        right: ${spacing.sm};
        font-size: ${fontSize.lg};
        border: none;
        background: none;
        color: ${this.colors.text};
        cursor: pointer;
        padding: ${spacing.sm};
        border-radius: 4px;
        z-index: 1;
      `;

    button.addEventListener("mouseover", () => {
      button.style.backgroundColor = this.colors.hoverBg;
    });

    button.addEventListener("mouseout", () => {
      button.style.backgroundColor = "transparent";
    });

    button.addEventListener("click", () => this.close());
    return button;
  }

  private calculateWindowPosition(): { top: number; left: number } {
    const gap = 20;
    const windowWidth = 800;
    const windowHeight = Math.min(window.innerHeight * 0.8, 600);

    const existingWindows = document.querySelectorAll("[data-preview-window]");

    if (existingWindows.length === 0) {
      return {
        top: (window.innerHeight - windowHeight) / 2,
        left: (window.innerWidth - windowWidth) / 2,
      };
    }

    const lastWindow = existingWindows[
      existingWindows.length - 1
    ] as HTMLElement;
    const lastRect = lastWindow.getBoundingClientRect();

    let left = lastRect.right + gap;
    let top = lastRect.top;

    if (left + windowWidth > window.innerWidth) {
      const firstWindow = existingWindows[0] as HTMLElement;
      const firstRect = firstWindow.getBoundingClientRect();
      left = firstRect.left;
      top = lastRect.bottom + gap;

      if (top + windowHeight > window.innerHeight) {
        top = firstRect.top + gap;
        left = firstRect.left + gap;
      }
    }

    left = Math.max(gap, Math.min(left, window.innerWidth - windowWidth - gap));
    top = Math.max(gap, Math.min(top, window.innerHeight - windowHeight - gap));

    return { top, left };
  }

  private getMarkdownStyles(): string {
    return `
      .content-preview-markdown h1, 
      .content-preview-markdown h2, 
      .content-preview-markdown h3 { margin-top: 1.5em; margin-bottom: 0.5em; color: ${this.colors.text}; }
      .content-preview-markdown p { margin: 1em 0; color: ${this.colors.text}; }
      .content-preview-markdown code { background: ${this.colors.codeBg}; padding: 0.2em 0.4em; border-radius: 3px; color: ${this.colors.text}; }
      .content-preview-markdown pre { background: ${this.colors.codeBg}; padding: 1em; border-radius: 5px; overflow-x: auto; }
      .content-preview-markdown pre code { background: none; padding: 0; }
      .content-preview-markdown ul, .content-preview-markdown ol { padding-left: 2em; color: ${this.colors.text}; }
      .content-preview-markdown blockquote { border-left: 4px solid ${this.colors.border}; margin: 0; padding-left: 1em; color: ${this.colors.text}; }
      .content-preview-markdown table { border-collapse: collapse; width: 100%; }
      .content-preview-markdown th, .content-preview-markdown td { border: 1px solid ${this.colors.border}; padding: 8px; text-align: left; color: ${this.colors.text}; }
      .content-preview-markdown th { background-color: ${this.colors.codeBg}; }
    `;
  }

  public show(title: string, content: string, fileName: string): void {
    this.content.innerHTML = "";

    this.header.innerHTML = "";
    const titleElement = document.createElement("h2");
    titleElement.style.cssText = `
        margin: 0;
        font-size: ${fontSize.lg};
        font-weight: 600;
        color: ${this.colors.text};
      `;
    titleElement.textContent = title;
    this.header.appendChild(titleElement);

    const contentContainer = document.createElement("div");
    contentContainer.style.cssText = `
        padding: ${spacing.md};
        overflow-y: auto;
        flex: 1;
        min-height: 200px;
        max-height: calc(80vh - 100px);
        font-size: ${fontSize.sm};
        line-height: 1.5;
        color: ${this.colors.text};
      `;

    const language = this.getLanguageFromFileName(fileName);

    if (language === "markdown") {
      contentContainer.style.fontFamily =
        "system-ui, -apple-system, sans-serif";
      contentContainer.style.background = this.colors.background;
      contentContainer.style.whiteSpace = "normal";

      if (window.marked) {
        contentContainer.innerHTML = window.marked.parse(content);
      } else {
        contentContainer.textContent = content;
        console.warn("Marked library not available for markdown parsing");
      }

      this.markdownStyle = document.createElement("style");
      this.markdownStyle.textContent = this.getMarkdownStyles();
      contentContainer.classList.add("content-preview-markdown");
      document.head.appendChild(this.markdownStyle);
    } else {
      contentContainer.style.fontFamily = "monospace";
      contentContainer.style.background = this.colors.codeBg;
      contentContainer.style.whiteSpace = "pre";

      if (language !== "plaintext") {
        contentContainer.className = `language-${language}`;
        if (window.Prism && window.Prism.languages[language]) {
          contentContainer.innerHTML = window.Prism.highlight(
            content,
            window.Prism.languages[language],
            language
          );
        } else {
          contentContainer.textContent = content;
        }
      } else {
        contentContainer.textContent = content;
      }
    }

    this.closeButton = this.createCloseButton();

    this.content.appendChild(this.closeButton);
    this.content.appendChild(this.header);
    this.content.appendChild(contentContainer);

    const position = this.calculateWindowPosition();
    this.dialog.style.transform = "none";
    this.dialog.style.top = `${position.top}px`;
    this.dialog.style.left = `${position.left}px`;

    ContentPreview.windowCount++;
    this.dialog.style.zIndex = `${
      ContentPreview.baseZIndex + ContentPreview.windowCount
    }`;

    this.dialog.setAttribute("data-preview-window", "");

    this.dialog.style.display = "block";
    this.dialog.style.opacity = "0";
    setTimeout(() => {
      this.dialog.style.transition = "opacity 0.2s ease-out";
      this.dialog.style.opacity = "1";
    }, 0);

    this.isOpen = true;
  }

  public close(): void {
    if (!this.isOpen) return;

    this.dialog.style.opacity = "0";
    setTimeout(() => {
      this.dialog.style.display = "none";
      this.content.innerHTML = "";
      ContentPreview.windowCount--;
      if (this.markdownStyle) {
        this.markdownStyle.remove();
        this.markdownStyle = null;
      }
      this.closeButton = null;
    }, 200);

    this.isOpen = false;
  }

  public destroy(): void {
    ThemeManager.removeThemeChangeListener(this.updateTheme.bind(this));
    if (this.markdownStyle) {
      this.markdownStyle.remove();
    }
    this.draggableManager.destroy();
    this.dialog.remove();
  }
}
