/**
 * Copyright (c) 2024 Martin Bechard <martin.bechard@DevConsult.ca>
 * This software is licensed under the MIT License.
 * File: /Users/martinbechard/dev/claudeext/src/ui/components/DownloadWidgets.ts
 * This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
 *
 * UI widget utilities for the download table components
 * Note: Making UI elements as reusable as Lego blocks!
 */

import type { SearchResultInfo } from "../../types";
import { EditableCell } from "./EditableCell";
import { ProjectSearchService } from "../../services/ProjectSearchService";
import { SearchResultPreview } from "./SearchResultPreview";

// Base styles that can be used across components
const styles = {
  colors: {
    primary: "#0066cc",
    primaryHover: "#0052a3",
    border: "#ccc",
    text: "#333",
    textMuted: "#666",
    background: "#f8f9fa",
    backgroundMuted: "#dee2e6",
    error: "#dc3545",
    errorBackground: "#f8d7da",
    warning: "#ffc107",
    warningBackground: "#fff3cd",
    working: "#6c757d",
    workingBackground: "#e9ecef",
    cancelling: "#fd7e14",
    cancellingBackground: "#fff3e6",
  },
  spacing: {
    sm: "4px",
    md: "8px",
    lg: "12px",
    xl: "16px",
  },
  borderRadius: "4px",
  fontSize: {
    sm: "12px",
    md: "14px",
    lg: "16px",
  },
};

/**
 * Creates a styled table cell
 */
export function createTableCell(isHeader = false): HTMLTableCellElement {
  const cell = document.createElement(isHeader ? "th" : "td");
  cell.style.cssText = `
    padding: ${styles.spacing.md};
    border: 1px solid ${styles.colors.border};
    font-size: ${styles.fontSize.sm};
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    ${
      isHeader
        ? `
        background-color: ${styles.colors.background};
        font-weight: 600;
      `
        : ""
    }
  `;
  return cell;
}

/**
 * Creates a checkbox cell with consistent styling
 */
export function createCheckboxCell(
  isSelected: boolean = false
): HTMLTableCellElement {
  const cell = createTableCell();
  cell.style.textAlign = "center";

  const checkbox = document.createElement("input");
  checkbox.type = "checkbox";
  checkbox.checked = isSelected || false; // Ensure boolean value

  cell.appendChild(checkbox);
  return cell;
}

/**
 * Creates a styled empty state message
 */
export function createEmptyState(message: string): HTMLDivElement {
  const container = document.createElement("div");
  container.style.cssText = `
    text-align: center;
    padding: ${styles.spacing.xl};
    color: ${styles.colors.textMuted};
    background-color: ${styles.colors.background};
    border: 1px solid ${styles.colors.backgroundMuted};
    border-radius: ${styles.borderRadius};
    margin-top: ${styles.spacing.lg};
  `;
  container.textContent = message;
  return container;
}

/**
 * Creates a styled link element
 */
export function createLink(text: string, url: string): HTMLAnchorElement {
  const link = document.createElement("a");
  link.href = url;
  link.textContent = text;
  link.target = "_blank";
  link.style.cssText = `
    color: ${styles.colors.primary};
    text-decoration: none;
    margin-right: ${styles.spacing.md};
    font-size: ${styles.fontSize.md};
  `;

  link.addEventListener("mouseover", () => {
    link.style.textDecoration = "underline";
  });

  link.addEventListener("mouseout", () => {
    link.style.textDecoration = "none";
  });

  return link;
}

/**
 * Creates a styled button element
 */
export function createButton(
  text: string,
  onClick: () => void,
  options: { variant?: "primary" | "secondary" | "icon" | "danger" } = {}
): HTMLButtonElement {
  const button = document.createElement("button");
  button.textContent = text;

  const baseStyles = `
    cursor: pointer;
    border: none;
    font-size: ${styles.fontSize.md};
    transition: all 0.2s ease;
    display: inline-flex;
    align-items: center;
    justify-content: center;
  `;

  let variantStyles = "";
  switch (options.variant) {
    case "secondary":
      variantStyles = `
        background: ${styles.colors.background};
        color: ${styles.colors.text};
        padding: ${styles.spacing.md} ${styles.spacing.xl};
        border-radius: ${styles.borderRadius};
        border: 1px solid ${styles.colors.border};
      `;
      break;
    case "icon":
      variantStyles = `
        background: none;
        color: ${styles.colors.textMuted};
        padding: ${styles.spacing.sm};
      `;
      break;
    case "danger":
      variantStyles = `
        background: ${styles.colors.error};
        color: white;
        padding: ${styles.spacing.md} ${styles.spacing.xl};
        border-radius: ${styles.borderRadius};
      `;
      break;
    default: // primary
      variantStyles = `
        background: ${styles.colors.primary};
        color: white;
        padding: ${styles.spacing.md} ${styles.spacing.xl};
        border-radius: ${styles.borderRadius};
      `;
  }

  button.style.cssText = baseStyles + variantStyles;

  // Add hover effects
  button.addEventListener("mouseover", () => {
    if (options.variant === "icon") {
      button.style.color = styles.colors.primary;
    } else if (options.variant === "secondary") {
      button.style.backgroundColor = styles.colors.backgroundMuted;
    } else if (options.variant === "danger") {
      button.style.backgroundColor = styles.colors.errorBackground;
    } else {
      button.style.backgroundColor = styles.colors.primaryHover;
    }
  });

  button.addEventListener("mouseout", () => {
    if (options.variant === "icon") {
      button.style.color = styles.colors.textMuted;
    } else if (options.variant === "secondary") {
      button.style.backgroundColor = styles.colors.background;
    } else if (options.variant === "danger") {
      button.style.backgroundColor = styles.colors.error;
    } else {
      button.style.backgroundColor = styles.colors.primary;
    }
  });

  button.addEventListener("click", onClick);
  return button;
}

/**
 * Creates a container for buttons with consistent styling
 */
export function createButtonContainer(): HTMLDivElement {
  const container = document.createElement("div");
  container.style.cssText = `
    display: flex;
    gap: ${styles.spacing.md};
    margin-top: ${styles.spacing.lg};
  `;
  return container;
}

/**
 * Creates a date cell with consistent formatting
 */
export function createDateCell(date: string | undefined): HTMLTableCellElement {
  const cell = createTableCell();

  if (date) {
    const formattedDate = new Date(date).toLocaleString(undefined, {
      year: "numeric",
      month: "short",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
    });
    cell.textContent = formattedDate;
    cell.title = new Date(date).toLocaleString(undefined, {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
      timeZoneName: "short",
    });
  }

  cell.style.cssText += `
    color: ${styles.colors.textMuted};
    font-size: ${styles.fontSize.sm};
    text-align: center;
  `;

  return cell;
}

/**
 * Creates a preview (eye) icon SVG element
 */
export function createPreviewIcon({
  size = 16,
  color = styles.colors.textMuted,
}: {
  size?: number;
  color?: string;
} = {}): SVGElement {
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  svg.setAttribute("width", size.toString());
  svg.setAttribute("height", size.toString());
  svg.setAttribute("viewBox", "0 0 24 24");
  svg.setAttribute("fill", "none");
  svg.setAttribute("stroke", color);
  svg.setAttribute("stroke-width", "2");
  svg.innerHTML = `
    <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
    <circle cx="12" cy="12" r="3"></circle>
  `;
  return svg;
}

/**
 * Creates an error icon SVG element
 */
function createErrorIcon({
  size = 16,
  color = styles.colors.error,
}: {
  size?: number;
  color?: string;
} = {}): SVGElement {
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  svg.setAttribute("width", size.toString());
  svg.setAttribute("height", size.toString());
  svg.setAttribute("viewBox", "0 0 24 24");
  svg.setAttribute("fill", "none");
  svg.setAttribute("stroke", color);
  svg.setAttribute("stroke-width", "2");
  svg.innerHTML = `
    <circle cx="12" cy="12" r="10"></circle>
    <line x1="12" y1="8" x2="12" y2="12"></line>
    <line x1="12" y1="16" x2="12.01" y2="16"></line>
  `;
  return svg;
}

/**
 * Creates a preview button with icon
 */
export function createPreviewButton(onClick: () => void): HTMLButtonElement {
  const button = createButton("", onClick, { variant: "icon" });
  button.title = "Preview conversation";
  button.appendChild(createPreviewIcon());
  return button;
}

/**
 * Creates a name cell with preview and edit functionality
 */
export function createNameCell(
  name: string,
  url?: string,
  onPreview?: () => void,
  onRename?: (newName: string) => void
): HTMLTableCellElement {
  const cell = createTableCell();
  let currentContent: HTMLElement;

  function createNormalView(): HTMLElement {
    const container = document.createElement("div");
    container.style.cssText = `
      display: flex;
      align-items: center;
      gap: ${styles.spacing.md};
    `;

    if (url) {
      container.appendChild(createLink(name, url));
    } else {
      const text = document.createElement("span");
      text.textContent = name;
      container.appendChild(text);
    }

    if (onPreview) {
      container.appendChild(createPreviewButton(onPreview));
    }

    if (onRename) {
      container.appendChild(createEditButton(() => switchToEditMode()));
    }

    return container;
  }

  function switchToEditMode(): void {
    const editableCell = new EditableCell({
      initialValue: name,
      validator: validateFilePath,
      onSave: (newValue) => {
        onRename?.(newValue);
        switchToNormalMode();
      },
      onCancel: () => switchToNormalMode(),
    });

    currentContent.replaceWith(editableCell.getElement());
    currentContent = editableCell.getElement();
    editableCell.focus();
  }

  function switchToNormalMode(): void {
    const normalView = createNormalView();
    currentContent.replaceWith(normalView);
    currentContent = normalView;
  }

  // Start with normal view
  currentContent = createNormalView();
  cell.appendChild(currentContent);

  return cell;
}

/**
 * Creates a cell displaying search result information with expandable content
 */
export function createSearchResultCell(
  searchResult?: SearchResultInfo,
  error?: string,
  preview?: SearchResultPreview,
  allResults?: SearchResultInfo[]
): HTMLTableCellElement {
  const cell = createTableCell();

  // Handle working state
  if (error === "Working..." || error === "Cancelling...") {
    const workingContainer = document.createElement("div");
    const isWorking = error === "Working...";
    workingContainer.style.cssText = `
      padding: ${styles.spacing.md};
      color: ${isWorking ? styles.colors.working : styles.colors.cancelling};
      font-size: ${styles.fontSize.sm};
      background: ${
        isWorking
          ? styles.colors.workingBackground
          : styles.colors.cancellingBackground
      };
      border-radius: ${styles.borderRadius};
      border-left: 3px solid ${
        isWorking ? styles.colors.working : styles.colors.cancelling
      };
      display: flex;
      align-items: center;
      gap: ${styles.spacing.md};
    `;

    const statusContainer = document.createElement("div");
    statusContainer.style.cssText = `
      display: flex;
      align-items: center;
      gap: ${styles.spacing.md};
    `;

    // Add loading spinner
    const spinner = document.createElement("div");
    spinner.style.cssText = `
      width: 12px;
      height: 12px;
      border: 2px solid ${
        isWorking ? styles.colors.working : styles.colors.cancelling
      };
      border-top-color: transparent;
      border-radius: 50%;
      animation: spin 1s linear infinite;
    `;
    const style = document.createElement("style");
    style.textContent = `
      @keyframes spin {
        to { transform: rotate(360deg); }
      }
    `;
    document.head.appendChild(style);

    statusContainer.appendChild(spinner);
    statusContainer.appendChild(document.createTextNode(error));
    workingContainer.appendChild(statusContainer);

    cell.appendChild(workingContainer);
    return cell;
  }

  // Handle error state
  if (error && error !== "No match found") {
    const errorContainer = document.createElement("div");
    errorContainer.style.cssText = `
      padding: ${styles.spacing.md};
      color: ${styles.colors.error};
      font-size: ${styles.fontSize.sm};
      background: ${styles.colors.errorBackground};
      border-radius: ${styles.borderRadius};
      border-left: 3px solid ${styles.colors.error};
      display: flex;
      align-items: center;
      gap: ${styles.spacing.md};
      cursor: pointer;
    `;

    // Add error icon that shows details on click
    const errorButton = createButton(
      "",
      () => {
        preview?.show(error);
      },
      { variant: "icon" }
    );
    errorButton.title = "View error details";
    errorButton.appendChild(createErrorIcon());

    errorContainer.appendChild(errorButton);
    errorContainer.appendChild(document.createTextNode(error));

    cell.appendChild(errorContainer);
    return cell;
  }

  // Handle "No match found" state
  if (error === "No match found") {
    const noMatchContainer = document.createElement("div");
    noMatchContainer.style.cssText = `
      padding: ${styles.spacing.md};
      color: ${styles.colors.warning};
      font-size: ${styles.fontSize.sm};
      background: ${styles.colors.warningBackground};
      border-radius: ${styles.borderRadius};
      border-left: 3px solid ${styles.colors.warning};
    `;
    noMatchContainer.textContent = "No match found";
    cell.appendChild(noMatchContainer);
    return cell;
  }

  if (!searchResult) {
    return cell;
  }

  // Create clickable container for search result
  const container = document.createElement("div");
  container.style.cssText = `
    display: flex;
    flex-direction: column;
    gap: ${styles.spacing.sm};
    max-width: 400px;
    min-width: 200px;
    cursor: pointer;
    padding: ${styles.spacing.md};
    border-radius: ${styles.borderRadius};
    transition: background-color 0.2s ease;
  `;

  // Add hover effect
  container.addEventListener("mouseover", () => {
    container.style.backgroundColor = styles.colors.background;
  });
  container.addEventListener("mouseout", () => {
    container.style.backgroundColor = "transparent";
  });

  // Add click handler to show preview
  container.addEventListener("click", () => {
    preview?.show(allResults || [searchResult]); // Use all results if available, otherwise wrap single result
  });

  // Add match reason with truncation
  const reason = document.createElement("div");
  reason.textContent = searchResult.matchReason;
  reason.style.cssText = `
    font-size: ${styles.fontSize.sm};
    color: ${styles.colors.text};
    line-height: 1.4;
    display: -webkit-box;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 2;
    overflow: hidden;
  `;
  container.appendChild(reason);

  // Add snippet preview with truncation
  const snippet = document.createElement("div");
  snippet.textContent = searchResult.relevantSnippet;
  snippet.style.cssText = `
    font-size: ${styles.fontSize.sm};
    color: ${styles.colors.textMuted};
    font-style: italic;
    background: ${styles.colors.background};
    padding: ${styles.spacing.md};
    border-radius: ${styles.borderRadius};
    border-left: 3px solid ${styles.colors.primary};
    line-height: 1.4;
    display: -webkit-box;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 2;
    overflow: hidden;
  `;
  container.appendChild(snippet);

  // Add "Click to view details" hint with result count if multiple
  const hint = document.createElement("div");
  hint.style.cssText = `
    font-size: ${styles.fontSize.sm};
    color: ${styles.colors.primary};
    display: flex;
    align-items: center;
    gap: ${styles.spacing.sm};
  `;
  hint.appendChild(createPreviewIcon({ color: styles.colors.primary }));

  const resultCount = allResults?.length || 1;
  hint.appendChild(
    document.createTextNode(
      resultCount > 1
        ? `Click to view ${resultCount} results`
        : "Click to view details"
    )
  );
  container.appendChild(hint);

  cell.appendChild(container);
  return cell;
}

/**
 * Creates an edit icon SVG element
 */
function createEditIcon({
  size = 16,
  color = styles.colors.textMuted,
}: {
  size?: number;
  color?: string;
} = {}): SVGElement {
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  svg.setAttribute("width", size.toString());
  svg.setAttribute("height", size.toString());
  svg.setAttribute("viewBox", "0 0 24 24");
  svg.setAttribute("fill", "none");
  svg.setAttribute("stroke", color);
  svg.setAttribute("stroke-width", "2");
  svg.innerHTML = `
    <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
    <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
  `;
  return svg;
}

/**
 * Creates an edit button with icon
 */
function createEditButton(onClick: () => void): HTMLButtonElement {
  const button = createButton("", onClick, { variant: "icon" });
  button.title = "Edit name";
  button.appendChild(createEditIcon());
  return button;
}

/**
 * Validates a file path
 */
function validateFilePath(value: string): string | null {
  if (!value) {
    return "Path cannot be empty";
  }

  // Check for invalid characters
  const invalidChars = /[\x00-\x1F]/g; // Allow slashes and other path chars
  if (invalidChars.test(value)) {
    return "Path contains invalid characters";
  }

  return null;
}
