/**
 * Copyright (c) 2024 Martin Bechard <martin.bechard@DevConsult.ca>
 * This software is licensed under the MIT License.
 * File: /Users/martinbechard/dev/claudeext/src/ui/components/HelpManager.ts
 * This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
 */

/**
 * Manages help text display and formatting for the extension.
 */
export class HelpManager {
  private readonly outputElement: HTMLElement;
  private static readonly HELP_TEXT = `
    ClaudeScript v1.5
    
    1. Simple Prompt:
    Just type your prompt and it will be sent once.
    
    2. Commands:
    
    Basic Commands:
    /d[ocs] - List available documents
    /p[roject] - List conversations in current project
    
    Content Commands:
    /c[onversation] - Export conversation without artifacts
    /c[onversation] /a[rtifacts] - Export conversation including artifacts
    /c[onversation] /m[ultiple] - Export artifacts as separate files
    /a[rtifacts] - Export only artifacts as markdown
    /a[rtifacts] /m[ultiple] - Export artifacts as separate files
    
    Project Commands:
    /sp[search_project] [text] - Search project conversations
    /qp[query_project] prompt - Query all conversations
    
    Alias Commands:
    /al[ias] @name text - Create or update an alias
    /da[delete_alias] @name - Delete an alias
    /la[list_alias] - List all aliases
    
    3. Loop Command Format:
    /repeat [/max number] [/stop_if condition]
    or
    /repeat [/max number] [/stop_if_not condition]
    
    Examples:
    Simple prompt:
    Tell me a joke
    
    With aliases:
    /alias @joke Tell me your best joke
    @joke
    
    With repeat and max tries:
    /repeat /max 3 /stop_if success
    Tell me a joke
    
    With repeat until condition:
    /repeat /stop_if laugh
    Tell me a joke
    
    Note: All command keywords now start with / for consistency`.trim();

  /**
   * Creates a new HelpManager instance.
   * @param outputElement - Element to display help text in
   */
  constructor(outputElement: HTMLElement) {
    this.outputElement = outputElement;
  }

  /**
   * Displays the help text in the output element.
   */
  public show(): void {
    this.outputElement.innerHTML = "";
    HelpManager.HELP_TEXT.split("\n").forEach((line) => {
      const div = document.createElement("div");
      div.textContent = line;
      div.style.whiteSpace = "pre";
      this.outputElement.appendChild(div);
    });
  }

  /**
   * Updates the help text content dynamically.
   * @param newText - New help text content
   */
  public updateContent(newText: string): void {
    this.outputElement.innerHTML = "";
    newText
      .trim()
      .split("\n")
      .forEach((line) => {
        const div = document.createElement("div");
        div.textContent = line;
        div.style.whiteSpace = "pre";
        this.outputElement.appendChild(div);
      });
  }

  /**
   * Clears the help text display.
   */
  public clear(): void {
    this.outputElement.innerHTML = "";
  }
}
