/**
 * Copyright (c) 2024 Martin Bechard <martin.bechard@DevConsult.ca>
 * This software is licensed under the MIT License.
 * File: src/utils/commands/parseStopConditions.ts
 * This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
 */

import { stat } from "fs";
import { ParsedCommandLine, ScriptStatement, StopCondition } from "../../types";

/**
 * Parses a stop condition from command text
 */
export function parseStopConditionCommand(
  parsedCommandLine: ParsedCommandLine
): ScriptStatement {
  const target = parsedCommandLine.prompt;

  const type = parsedCommandLine.command === "stop_if" ? "if" : "if_not";

  const statement = new ScriptStatement({
    isCommand: true,
    command: parsedCommandLine.command,
    options: { stopConditions: [{ target, type }] },
  });

  return statement;
}
