/**
 * Copyright (c) 2024 Martin Bechard <martin.bechard@DevConsult.ca>
 * This software is licensed under the MIT License.
 * File: src/utils/commands/parseProjectCommands.ts
 * This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
 */

import { ParsedCommandLine, ScriptStatement } from "../../types";

/**
 * Parses a basic project command
 */
export function parseProjectCommand(
  parsedCommandLine: ParsedCommandLine
): ScriptStatement {
  return new ScriptStatement({
    isCommand: true,
    command: "project",
    prompt: parsedCommandLine.prompt.trim(),
  });
}

/**
 * Parses a project search command with optional search text and number of results
 */
export function parseSearchProjectCommand(
  parsedCommandLine: ParsedCommandLine
): ScriptStatement {
  const { prompt, options } = parsedCommandLine;

  if (!prompt.trim()) {
    throw new Error("Search project command requires search text");
  }

  return new ScriptStatement({
    isCommand: true,
    command: "search_project",
    searchText: prompt.trim(),
    options: {
      numResults: options.numResults || "5", // Default to 5 results if not specified
    },
  });
}

/**
 * Parses a project query command with required prompt
 */
export function parseQueryProjectCommand(
  parsedCommandLine: ParsedCommandLine
): ScriptStatement {
  const { prompt } = parsedCommandLine;

  if (!prompt.trim()) {
    throw new Error("Query project command requires a prompt");
  }

  return new ScriptStatement({
    isCommand: true,
    command: "query_project",
    options: {},
    prompt: prompt.trim(),
  });
}
