/**
 * Copyright (c) 2024 Martin Bechard <martin.bechard@DevConsult.ca>
 * This software is licensed under the MIT License.
 * File: src/utils/ElementWaiter.ts
 * This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
 *
 * Utility class for waiting for DOM elements to appear with robust timeout handling.
 * Fun fact: Even the most patient element waiter sometimes wishes elements would show up faster!
 */

export class ElementWaiter {
  private static readonly TIMEOUT = 30000;

  /**
   * Wait for a single element to appear
   * @param selector CSS selector to wait for
   * @returns Promise resolving to the found element
   * @throws Error if element not found within timeout
   */
  public static waitForElement(selector: string): Promise<Element> {
    console.log(`Waiting for element: ${selector}`);

    return new Promise((resolve, reject) => {
      // Set timeout
      const timeout = setTimeout(() => {
        observer.disconnect();
        reject(new Error(`Timeout waiting for element: ${selector}`));
      }, this.TIMEOUT);

      // Check immediately first
      const element = document.querySelector(selector);
      if (element) {
        console.log(`Element found immediately: ${selector}`);
        clearTimeout(timeout);
        return resolve(element);
      }

      // Watch for changes
      const observer = new MutationObserver(() => {
        const element = document.querySelector(selector);
        if (element) {
          console.log(`Element found after mutation: ${selector}`);
          clearTimeout(timeout);
          observer.disconnect();
          resolve(element);
        }
      });

      // Start observing
      observer.observe(document.body, {
        childList: true,
        subtree: true,
      });
    });
  }

  /**
   * Wait for both required Claude interface elements
   * @returns Promise resolving when both elements are found
   * @throws Error if either element not found within timeout
   */
  public static async waitForRequiredElements(): Promise<void> {
    console.log("Waiting for Claude chat interface...");

    // Wait for container first
    await this.waitForElement(".chat-messages-container");
    console.log("Chat container found");

    // Then wait for input
    await this.waitForElement(".prompt-textarea");
    console.log("Input area found");
  }
}
