/**
 * Copyright (c) 2024 Martin Bechard <martin.bechard@DevConsult.ca>
 * This software is licensed under the MIT License.
 * File: /src/utils/getHeaders.ts
 * This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
 */

export function getHeaders(): HeadersInit {
  return {
    Accept: "*/*",
    "Accept-Encoding": "gzip, deflate, br, zstd",
    "Accept-Language": "en-US,en;q=0.9,fr-CA;q=0.8,fr;q=0.7",
    "Anthropic-Client-Sha": "unknown",
    "Anthropic-Client-Version": "unknown",
    "Cache-Control": "no-cache",
    "Content-Type": "application/json",
    Origin: "https://claude.ai",
    Pragma: "no-cache",
    Referer: "https://claude.ai/",
    "Sec-Ch-Ua":
      '"Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"',
    "Sec-Ch-Ua-Mobile": "?0",
    "Sec-Ch-Ua-Platform": '"macOS"',
    Priority: "u=1, i",
  };
}
