"use strict";
// Copyright (c) 2024 Martin Bechard martin.bechard@DevConsult.ca
// This software is licensed under the MIT License.
// Path: src/analyzeConversations.ts
// This was generated by Claude Sonnet 3.5, with the assistance of my human mentor
// Script to analyze conversation data from a JSON file
// "I count characters so you don't have to!"
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return g.next = verb(0), g["throw"] = verb(1), g["return"] = verb(2), typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
var ConversationAnalyzer_1 = require("./ConversationAnalyzer");
var promises_1 = require("fs/promises");
function analyzeFile(filePath) {
    return __awaiter(this, void 0, void 0, function () {
        var data, analyzer, results, error_1;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0:
                    _a.trys.push([0, 2, , 3]);
                    return [4 /*yield*/, promises_1.default.readFile(filePath, "utf8")];
                case 1:
                    data = _a.sent();
                    analyzer = ConversationAnalyzer_1.ConversationAnalyzer.fromJson(data);
                    results = analyzer.analyze();
                    // Print results in a formatted way
                    console.log("Conversation Analysis Results\n");
                    results.conversationMetrics.forEach(function (conv) {
                        console.log("Conversation: ".concat(conv.conversationName, " (").concat(conv.conversationId, ")"));
                        console.log("Message Lengths:");
                        conv.messageLengths.forEach(function (msg) {
                            console.log("  Message ".concat(msg.messageId, ": ").concat(msg.length, " characters"));
                        });
                        console.log("Longest Message: ".concat(conv.longestMessage.length, " characters (ID: ").concat(conv.longestMessage.messageId, ")"));
                        console.log("Total Size: ".concat(conv.totalSize, " characters\n"));
                    });
                    console.log("Overall Total Size: ".concat(results.totalSize, " characters"));
                    return [3 /*break*/, 3];
                case 2:
                    error_1 = _a.sent();
                    console.error("Error analyzing file:", error_1);
                    process.exit(1);
                    return [3 /*break*/, 3];
                case 3: return [2 /*return*/];
            }
        });
    });
}
// Get file path from command line arguments
var filePath = process.argv[2];
if (!filePath) {
    console.error("Please provide a file path as an argument");
    process.exit(1);
}
analyzeFile(filePath);
